name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x 
  
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Interfaces/ContractSlicer 

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Interfaces/ContractSlicer 

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Interfaces/ContractSlicer 